services:
  - type: web
    name: edulog_project
    workingDirectory: /opt/render/project/src/edulog_backend
    startCommand: gunicorn edulog.wsgi:application --bind 0.0.0.0:$PORT
    postDeployCommand: |
      echo "Running migrations..."
      python manage.py makemigrations
      python manage.py migrate

envVars:
  - key: SECRET_KEY
    generateValue: true 
  - key: DEBUG
    value: 'False'
  - key: ALLOWED_HOSTS
    value: 'edulog-project.onrender.com'  
  - key: DATABASE_URL
    fromDatabase:
      name: edulog_db  
      property: connectionString
  - key: CSRF_TRUSTED_ORIGINS
    value: 'https://edulog-project.onrender.com'
  - key: CORS_ALLOWED_ORIGINS
    value: 'https://myvercel.vercel.app'  
  - key: DISABLE_COLLECTSTATIC
    value: '0'
  - key: STATIC_ROOT
    value: '/opt/render/project/src/edulog_backend/staticfiles'
  - key: PYTHONPATH
    value: /opt/render/project/src/edulog_backend  
