# Generated by Django 5.1.7 on 2025-04-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edulog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='edulog_app_customuser',
        ),
    ]
